FROM ubuntu:latest
RUN apt-get update \
&& apt-get install -y locales  \
&& apt-get install -y mariadb-client \
&& apt-get install -y telnet \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

COPY command2 /tmp
RUN chmod 755 /tmp/command2
CMD /tmp/command2


